#security:
#  oauth2:
#    client:
#       clientId: Ov23lilloISxjfTykY4L
#       clientSecret: 78663daad9dc20ce278b9615288a18c42755f6fb
#       accessTokenUri: https://github.com/login/oauth/access_token
#       userAuthorizationUri: https://github.com/login/oauth/authorize
#       clientAuthenticationScheme: form
#    resource:
#      user-info-uri: https://api.github.com/user
#      prefer-token-info: false 
      
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: Ov23lilloISxjfTykY4L
#            client-secret: 78663daad9dc20ce278b9615288a18c42755f6fb
#            scope: profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#            client-name: Google
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: Ov23lilloISxjfTykY4L
#            client-secret: 78663daad9dc20ce278b9615288a18c42755f6fb
#            scope: user, repo  # Adjust the scope as needed
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            authorization-grant-type: authorization_code
#            client-name: GitHub
#        provider:
#          github:
#            authorization-uri: https://github.com/login/oauth/authorize
#            token-uri: https://github.com/login/oauth/access_token
#            user-info-uri: https://api.github.com/user
#            user-name-attribute: id
